package ui.launch;

public interface IMRLaunchConfigurationConstants {

	String ACCOUNT_NUMBER = "ACCOUNT_NUMBER";
	String ACCESS_KEY ="ACCESS_KEY";
	String SECRET_KEY="ACCESS_KEY";
	String HADOOP_DISTRIBUTION="HADOOP_DISTRIBUTION";
	String MR_FILE_NAME="MR_FILE_NAME";
	String MR_JAVA_DEBUG="MR_JAVA_DEBUG";
	//prateek
	String HADOOP_INPUT_FILE="HADOOP_INPUT_FILE";
	String HADOOP_OUTPUT_FILE="HADOOP_OUTPUT_FILE";
	String EC2_HOME="EC2_HOME";
	String AMAZON_CLUSTER_NAME="AMAZON_CLUSTER_NAME";
	String NUMBER_OF_SLAVES="NUMBER_OF_SLAVES";
	String TOKENIZER = "StringTokenizer";
	String EXECUTE_IN_EC2 = "IN_EC2";
	
}