/*
* generated by Xtext
*/
package cs.ua.edu.segroup.ui.contentassist;

import cs.ua.edu.segroup.ui.contentassist.AbstractMDPProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MDPProposalProvider extends AbstractMDPProposalProvider {

}
