
/*
 * generated by Xtext
 */
 
package cs.ua.edu.segroup.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class MDPExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return cs.ua.edu.segroup.ui.internal.MDPActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return cs.ua.edu.segroup.ui.internal.MDPActivator.getInstance().getInjector("cs.ua.edu.segroup.MDP");
	}
	
}
