/*
 * generated by Xtext
 */
package cs.ua.edu.se;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MapRedoopRuntimeModule extends cs.ua.edu.se.AbstractMapRedoopRuntimeModule {

}
