/*
* generated by Xtext
*/
package cs.ua.edu.se.ui.contentassist;

import cs.ua.edu.se.ui.contentassist.AbstractMapRedoopProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MapRedoopProposalProvider extends AbstractMapRedoopProposalProvider {

}
