/*
 * generated by Xtext
 */
package cs.ua.edu.segroup.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDPUiModule extends cs.ua.edu.segroup.ui.AbstractMDPUiModule {
	public MDPUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
