/*
 * generated by Xtext
 */
package cs.ua.edu.se.ui;

import java.net.URL;

import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.swt.graphics.Image;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MapRedoopUiModule extends cs.ua.edu.se.ui.AbstractMapRedoopUiModule {
	public MapRedoopUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	private static Image ec2Image = null;
	private static Image hadoopImage = null; 
    public static Image getImage(String image){
    	if(image.equals("ec2")){
	    	if(ec2Image!=null) return ec2Image;
	    	ec2Image = AbstractUIPlugin.imageDescriptorFromPlugin("cs.ua.edu.segroup.mapredoop.ui", "icons/ec2.png").createImage();
	    	return ec2Image;
    	}
     	if(image.equals("hadoop")){
        	if(hadoopImage!=null) return hadoopImage;
        	hadoopImage = AbstractUIPlugin.imageDescriptorFromPlugin("cs.ua.edu.segroup.mapredoop.ui", "icons/hadoop.png").createImage();
        	return hadoopImage;
        	}

    	return null;
    }

}
