/*
* generated by Xtext
*/
package cs.ua.edu.se.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MapRedoopTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
